"""Add categories and update models

Revision ID: 49842ad5ad0b
Revises: 
Create Date: 2026-05-20 19:00:42.336281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49842ad5ad0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_loans_book_id', table_name='loans')
    op.drop_index('ix_loans_id', table_name='loans')
    op.drop_index('ix_loans_user_id', table_name='loans')
    op.drop_table('loans')
    op.drop_index('ix_books_id', table_name='books')
    op.drop_index('ix_books_isbn', table_name='books')
    op.drop_index('ix_books_title', table_name='books')
    op.drop_table('books')
    op.add_column('book', sa.Column('publisher', sa.String(length=100), nullable=True))
    op.add_column('book', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('book', sa.Column('pages', sa.Integer(), nullable=True))
    op.create_index('idx_book_title_author', 'book', ['title', 'author'], unique=False)
    op.add_column('loan', sa.Column('extended', sa.Boolean(), nullable=False))
    op.create_index('idx_loan_book_id', 'loan', ['book_id'], unique=False)
    op.create_index('idx_loan_return_date', 'loan', ['return_date'], unique=False)
    op.create_index('idx_loan_user_id', 'loan', ['user_id'], unique=False)
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'address')
    op.drop_column('user', 'phone')
    op.drop_index('idx_loan_user_id', table_name='loan')
    op.drop_index('idx_loan_return_date', table_name='loan')
    op.drop_index('idx_loan_book_id', table_name='loan')
    op.drop_column('loan', 'extended')
    op.drop_index('idx_book_title_author', table_name='book')
    op.drop_column('book', 'pages')
    op.drop_column('book', 'language')
    op.drop_column('book', 'publisher')
    op.create_table('books',
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('author', sa.VARCHAR(length=255), nullable=True),
    sa.Column('isbn', sa.VARCHAR(length=13), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('available_copies', sa.INTEGER(), nullable=True),
    sa.Column('total_copies', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_books_title', 'books', ['title'], unique=False)
    op.create_index('ix_books_isbn', 'books', ['isbn'], unique=1)
    op.create_index('ix_books_id', 'books', ['id'], unique=False)
    op.create_table('loans',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('returned_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loans_user_id', 'loans', ['user_id'], unique=False)
    op.create_index('ix_loans_id', 'loans', ['id'], unique=False)
    op.create_index('ix_loans_book_id', 'loans', ['book_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    # ### end Alembic commands ###
